import { QuizCard } from '@/types';

export const INTEREST_CARDS: QuizCard[] = [
  {
    id: 'i1',
    scenario: 'I love designing things — logos, posters, videos',
    emoji: '🎨',
    category: 'creative',
    type: 'interest',
    bgColour: '#FF6B9D',
  },
  {
    id: 'i2',
    scenario: 'I get excited about how computers and AI work',
    emoji: '💻',
    category: 'technology',
    type: 'interest',
    bgColour: '#00B4D8',
  },
  {
    id: 'i3',
    scenario: 'I enjoy helping people who are struggling',
    emoji: '🤝',
    category: 'people',
    type: 'interest',
    bgColour: '#A8DADC',
  },
  {
    id: 'i4',
    scenario: 'Protecting the planet genuinely matters to me',
    emoji: '🌍',
    category: 'nature',
    type: 'interest',
    bgColour: '#70C95E',
  },
  {
    id: 'i5',
    scenario: 'I think about starting a business or making money',
    emoji: '💡',
    category: 'business',
    type: 'interest',
    bgColour: '#FFB703',
  },
  {
    id: 'i6',
    scenario: 'Medical shows, hospitals, and how the body works fascinate me',
    emoji: '🩺',
    category: 'health',
    type: 'interest',
    bgColour: '#06D6A0',
  },
  {
    id: 'i7',
    scenario: 'I love music — playing it, making it, or discovering new artists',
    emoji: '🎵',
    category: 'creative',
    type: 'interest',
    bgColour: '#FF6B9D',
  },
  {
    id: 'i8',
    scenario: 'I do well in maths and enjoy solving logical problems',
    emoji: '🔢',
    category: 'science',
    type: 'interest',
    bgColour: '#7B5EA7',
  },
  {
    id: 'i9',
    scenario: 'Writing — stories, essays, scripts, blogs — is something I enjoy',
    emoji: '✍️',
    category: 'language',
    type: 'interest',
    bgColour: '#F4A261',
  },
  {
    id: 'i10',
    scenario: 'Gaming — especially understanding how games are designed and built',
    emoji: '🎮',
    category: 'technology',
    type: 'interest',
    bgColour: '#00B4D8',
  },
  {
    id: 'i11',
    scenario: 'I find it satisfying to explain things and help others learn',
    emoji: '📚',
    category: 'people',
    type: 'interest',
    bgColour: '#A8DADC',
  },
  {
    id: 'i12',
    scenario: 'I care about animal welfare and wildlife conservation',
    emoji: '🦁',
    category: 'nature',
    type: 'interest',
    bgColour: '#70C95E',
  },
  {
    id: 'i13',
    scenario: 'I\'m interested in how laws and justice systems work',
    emoji: '⚖️',
    category: 'business',
    type: 'interest',
    bgColour: '#9B72CF',
  },
  {
    id: 'i14',
    scenario: 'I love science experiments and figuring out why things happen',
    emoji: '🔬',
    category: 'science',
    type: 'interest',
    bgColour: '#7B5EA7',
  },
  {
    id: 'i15',
    scenario: 'Fashion, style, and creative visual expression excite me',
    emoji: '👗',
    category: 'creative',
    type: 'interest',
    bgColour: '#FF6B9D',
  },
  {
    id: 'i16',
    scenario: 'Space, astronomy, and the universe genuinely blow my mind',
    emoji: '🚀',
    category: 'technology',
    type: 'interest',
    bgColour: '#00B4D8',
  },
  {
    id: 'i17',
    scenario: 'Speaking or learning other languages feels natural to me',
    emoji: '🗺️',
    category: 'language',
    type: 'interest',
    bgColour: '#F4A261',
  },
  {
    id: 'i18',
    scenario: 'I enjoy sports, fitness, or physical challenges',
    emoji: '🏃',
    category: 'nature',
    type: 'interest',
    bgColour: '#70C95E',
  },
  {
    id: 'i19',
    scenario: 'Mental health and emotional wellbeing really matter to me',
    emoji: '🧠',
    category: 'health',
    type: 'interest',
    bgColour: '#06D6A0',
  },
  {
    id: 'i20',
    scenario: 'I find it interesting to understand why people make decisions',
    emoji: '🔍',
    category: 'health',
    type: 'interest',
    bgColour: '#06D6A0',
  },
];

export const SKILL_CARDS: QuizCard[] = [
  {
    id: 's1',
    scenario: 'When something goes wrong, I stay calm and work out a solution',
    emoji: '🧩',
    category: 'problem_solving',
    type: 'skill',
    bgColour: '#00B4D8',
  },
  {
    id: 's2',
    scenario: 'I\'m always coming up with new ideas or unusual approaches',
    emoji: '💡',
    category: 'creativity',
    type: 'skill',
    bgColour: '#FF6B9D',
  },
  {
    id: 's3',
    scenario: 'People enjoy talking to me and I enjoy talking to people',
    emoji: '💬',
    category: 'people_skills',
    type: 'skill',
    bgColour: '#A8DADC',
  },
  {
    id: 's4',
    scenario: 'I notice details others miss and I like getting things right',
    emoji: '🔍',
    category: 'detail_oriented',
    type: 'skill',
    bgColour: '#FFB703',
  },
  {
    id: 's5',
    scenario: 'In group projects, I naturally take charge and organise things',
    emoji: '👑',
    category: 'leadership',
    type: 'skill',
    bgColour: '#9B72CF',
  },
  {
    id: 's6',
    scenario: 'I pick up new technology and software quickly',
    emoji: '⚙️',
    category: 'technical',
    type: 'skill',
    bgColour: '#7B5EA7',
  },
  {
    id: 's7',
    scenario: 'I express myself clearly — in writing, speaking, or presenting',
    emoji: '🎤',
    category: 'communication',
    type: 'skill',
    bgColour: '#F4A261',
  },
  {
    id: 's8',
    scenario: 'I enjoy physical activity and don\'t mind working with my hands',
    emoji: '💪',
    category: 'physical',
    type: 'skill',
    bgColour: '#70C95E',
  },
  {
    id: 's9',
    scenario: 'I can tell when someone is upset and I know how to support them',
    emoji: '💛',
    category: 'empathy',
    type: 'skill',
    bgColour: '#06D6A0',
  },
  {
    id: 's10',
    scenario: 'I keep my work organised and always meet my deadlines',
    emoji: '📋',
    category: 'organisation',
    type: 'skill',
    bgColour: '#FF6B6B',
  },
];
